### ISSUE TITLE
gulp-util is now deprecated

### ISSUE THREAD

**Issue by JimmyMultani** [fritx/gulp-mail#7]
The team at Gulp have [officially](https://github.com/gulpjs/gulp-util) ended support for `gulp-util`.

Replacing this dependency should be an easy fix. I could make a pull request, if you'd like.

**Comment by fritx** [comment]
@JimmyMultani yes, thanks, really appreciated!
just received another PR on 1.17 -- https://github.com/fritx/gulp-eol/commits/master

**Comment by fritx** [comment]
@JimmyMultani 0.3.0 was out.

**Comment by JimmyMultani** [comment]
That's great news, thanks @fritx!
